# Generated by Django 3.2.7 on 2021-09-25 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20210925_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.TextField(default='Name'),
            preserve_default=False,
        ),
    ]
